# Generated by Django 4.2.5 on 2023-09-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_description_alter_post_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
