# Generated by Django 4.2.5 on 2023-10-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.AutoField>/'),
        ),
    ]
