# Generated by Django 4.2.5 on 2023-10-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_blogcomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewCount',
            field=models.IntegerField(default=0),
        ),
    ]
