# Generated by Django 4.2.5 on 2023-10-12 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_post_viewcount_viewcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewcount',
            name='cookie',
        ),
    ]
