# Generated by Django 4.2.5 on 2023-10-12 12:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0020_alter_viewcount_post_alter_viewcount_user_likes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dislikes',
            new_name='Dislike',
        ),
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
