# Generated by Django 4.2.5 on 2023-09-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contact_user_alter_contact_email_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
