# Generated by Django 4.2.5 on 2023-10-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('you', '0004_alter_notification_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='read',
            new_name='status',
        ),
    ]
